# Project Name
TARGET = TestHardware

# Sources
CPP_SOURCES = TestHardware.cpp

# Library Locations
LIBDAISY_DIR = ../../../libDaisy

# Includes FatFS source files within project.
# USE_FATFS = 1

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
